dist: bionic
language: node_js
services:
# This is required to run a headful chrome/chromium
  - xvfb
node_js:
  - 12
git:
  depth: 1
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
before_script:
  - "make"
  - "cd test"
