version: 2.1
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: services xvfb start # Turn on xvfb so headful chrome/chromium is possible
      - run: sysctl kernel.unprivileged_userns_clone=1
      - run: export TEST_WORKERS=2
      - run: make test
