version: 2.1
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt-get install -y xvfb # Install xvfb so headful chrome/chromium is possible
      - run: sudo sysctl kernel.unprivileged_userns_clone=1
      - run: npm ci
      - run: TEST_WORKERS=4 TEST_TIMEOUT=120000 TEST_RETRIES=2 make test
      - store_test_results:
          path: build/reports

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
